# Generated by Django 4.1.1 on 2022-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(verbose_name='End date')),
                ('end_time', models.TimeField(null=True, verbose_name='End time')),
                ('is_date_only', models.BooleanField()),
                ('days_left', models.DateField()),
            ],
        ),
    ]
