# Generated by Django 4.1.1 on 2023-07-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('day_counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='counter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_guest', False)), fields=('user', 'title'), name='unique_title_for_user'),
        ),
    ]
