# Generated by Django 4.1.1 on 2022-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='days_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
