# Generated by Django 4.1.1 on 2022-09-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0002_alter_counter_days_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
