# Generated by Django 4.1.1 on 2022-09-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0003_counter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
