# Generated by Django 4.1.1 on 2022-09-16 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0004_counter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='counter',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
    ]
