# Generated by Django 4.1.1 on 2022-09-16 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0005_counter_guid_alter_counter_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
