# Generated by Django 4.1.1 on 2022-09-16 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0006_alter_counter_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Unique Id'),
        ),
    ]
