# Generated by Django 4.1.1 on 2022-09-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0007_alter_counter_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='is_guest',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
