# Generated by Django 4.1.1 on 2022-09-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0009_counter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='name',
        ),
        migrations.AddField(
            model_name='counter',
            name='title',
            field=models.CharField(default='aa', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
