# Generated by Django 4.1.1 on 2022-09-26 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0011_alter_counter_id_alter_counter_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unique Id'),
        ),
    ]
