# Generated by Django 4.1.1 on 2022-09-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0013_remove_counter_is_date_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='days_left',
        ),
    ]
