# Generated by Django 4.1.1 on 2022-09-27 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('day_counter', '0014_remove_counter_days_left'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counter',
            unique_together={('user', 'title')},
        ),
    ]
