# Generated by Django 4.1.1 on 2022-09-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0015_alter_counter_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counter',
            unique_together=set(),
        ),
    ]
