# Generated by Django 4.1.1 on 2022-09-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0016_alter_counter_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='counter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_guest', False)), fields=('user', 'title'), name='unique_title_for_user'),
        ),
    ]
