# Generated by Django 4.1.1 on 2023-07-08 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('day_counter', '0018_counter_is_date_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
