# Generated by Django 4.1.1 on 2023-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_counter', '0019_counter_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
