# Generated by Django 4.1.1 on 2023-07-18 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(verbose_name='End date')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('is_date_only', models.BooleanField(default=False, verbose_name='is time only')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unique Id')),
                ('is_guest', models.BooleanField(default=True)),
            ],
        ),
    ]
