# Generated by Django 4.1.1 on 2023-07-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="reminder_days",
            field=models.IntegerField(
                default=0, verbose_name="Days to remind before a counter ends"
            ),
        ),
    ]
